[package]
name = "mode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
chrono = "0.4.31"
colored = "2.0.4"
firebase-rs = "2.0.9"
rand = "0.8.5"
